spring.application.name=control_merca
spring.datasource.url=jdbc:mysql://localhost:3306/control_merca?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=201600
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect